name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          REPO_URL=$(echo "https://github.com/${GITHUB_REPOSITORY}" | sed "s|://|://x-access-token:${GITHUB_TOKEN}@|g")
          git clone --bare $REPO_URL

      - name: Set git config
        run: |
          ls
          cd REPO_NAME=$(basename ${GITHUB_REPOSITORY}).git
          git config user.email "66495214+ebarooni.noreply@barooni.dev"
          git config user.name "Ehsan Barooni"

      - name: Mirror to GitLab
        env:
          GITLAB_MIRROR_TOKEN: ${{ secrets.GITLAB_MIRROR_TOKEN }}
        run: |
          ls
          cd REPO_NAME=$(basename ${GITHUB_REPOSITORY}).git
          GITLAB_REPO="https://gitlab.com/ebarooni/useful-links.git"
          git remote add gitlab https://oauth2:${GITLAB_MIRROR_TOKEN}@${GITLAB_REPO#https://}
          git push --mirror gitlab
