name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set git config
        run: |
          echo "Started"
          echo "git version: ${{ git --version }}."
          echo "email: ${{ git config user.email }}."
          echo "name: ${{ git config user.name }}."
          git config user.email "66495214+ebarooni.noreply@barooni.dev"
          git config user.name "Ehsan Barooni"

      - name: Mirror to GitLab
        env:
          GITLAB_MIRROR_TOKEN: ${{ secrets.GITLAB_MIRROR_TOKEN }}
        run: |
          GITLAB_REPO="https://gitlab.com/ebarooni/useful-links.git"
          git remote add gitlab https://oauth2:${GITLAB_MIRROR_TOKEN}@${GITLAB_REPO#https://}
          git push --mirror gitlab
